Week 1
ClevertecFrontendLab/sprint1-eTsy30 pull request #1
Opened 2023-01-31 16:04 UTC by eTsy30

2023-01-31 16:07 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675181229/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675181229/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675181229/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-01-31 16:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675181950/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675181950/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675181950/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-01-31 17:02 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675184561/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675184561/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675184561/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-01-31 17:32 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675186351/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675186351/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675186351/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-01-31 17:45 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187152/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187152/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187152/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-01-31 17:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187210/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187210/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187210/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-01-31 17:49 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187342/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187342/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187342/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-01-31 17:50 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187407/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187407/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187407/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187407/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187407/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187407/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187407/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187407/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675187407/content-window.png)

2023-01-31 17:56 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215843421-a3b1f522-8184-4f9b-b142-075e7d40152e.png)
проверти размер карточки, возможно у вас стоят размеры в константах что то типо width: 300px; это плохо для адаптива

2023-01-31 17:57 UTC, SergeyGlazun commented
![image](https://user-images.githubusercontent.com/70904466/215843697-ac1a9276-2158-4586-b286-4476e2c4401f.png)
обратите внимание активный раздел должен выделяться тесктом, если вы использовали <NavLink удобно щздать через .classActive

2023-01-31 17:58 UTC, SergeyGlazun commented
![image](https://user-images.githubusercontent.com/70904466/215844044-a4beb14e-0f90-4a30-b5e0-576cce8bdf7d.png)
проверти пути. Если нет картинки можно подставлять картинку по умолчанию

2023-01-31 17:59 UTC, SergeyGlazun commented
![image](https://user-images.githubusercontent.com/70904466/215844383-b319912c-8b65-4946-ac3e-a9bc6e167843.png)
контент не должен вылазить за карточку

2023-02-01 12:25 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 6.
Количество непройденных тестов: 6.
***
**Test width 1440px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675254357/Test%20width%201440px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 1440px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675254357/Test%20width%201440px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675254357/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 320px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675254357/Test%20width%20320px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 768px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675254357/Test%20width%20768px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 768px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675254357/Test%20width%20768px%20--%20test%20layout%20content%20view%20(failed).png)

2023-02-01 12:39 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675255194/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675255194/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675255194/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675255194/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675255194/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675255194/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675255194/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675255194/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675255194/content-window.png)

2023-02-01 20:02 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675281774/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675281774/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675281774/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675281774/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675281774/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675281774/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675281774/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675281774/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675281774/content-window.png)

2023-02-01 20:12 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675282334/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675282334/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675282334/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675282334/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675282334/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675282334/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675282334/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675282334/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/eTsy30/1675282334/content-window.png)

2023-02-01 22:14 UTC, SergeyGlazun approved these changes

2023-02-01 22:14 UTC, SergeyGlazun commented
![image](https://user-images.githubusercontent.com/70904466/216175671-fbf59219-cfff-4fda-854b-643deecdd42b.png)
подправит отступы

2023-02-01 22:17 UTC, merged